Sliders - allow custom currency symbol and placement
smile-io/code-samples pull request #39
Opened 2020-12-10 16:11 UTC by tomnez

We're going to update the docs for our sliders to include a section on editing currency symbol and placement after copying and pasting these code snippets.

2020-12-10 16:40 UTC, GrizzlyNacho commented
I think we'll need to go a bit further with this. I like the extra flexibility you're highlighting for the merchant, but we'll want to point out where they can modify any of the English copy and probably also provide more robust tools to specify currency. The other details I'm thinking about here with currency formatting are: What symbol is used to separate decimals from whole numbers? How many decimal places are relevant? What should show to separate groups of place value?
Fake but representative example: $12,000.23 vs 12.000,5€

2020-12-10 19:16 UTC, tomnez commented
@GrizzlyNacho hm ok. The ticket was just about positioning the currency, so we want to point out every area where we have hard coded text and add docs to tell them they can modify these texts too? And we're ok with attaching another hard coded URL to a third party lib for formatting the currency?

2020-12-10 19:22 UTC, GrizzlyNacho commented
@tomnez The DE was just about the positioning on the currency, but it raised the issue that we don't handle translations in our code snippets for use in embedding in checkout across Shopify and BigCommerce. I can split the tickets if you like. 
Do you think we'd need a third party for the currency formatting? I'm open to that since it's nice not to need to maintain the code, but it does come at the cost of loading more on the merchant's checkout. Which do you think is better?

2020-12-16 09:55 UTC, vladucu commented on bigcommerce-points-slider/smile-points-slider.html
> +<script type="https://cdnjs.com/libraries/currencyformatter.js"></script>
what's the size of this lib? have we considered other options too?
just asking because it would be nice to be mindful when choosing this as a recommendation

2020-12-16 18:44 UTC, tomnez commented on bigcommerce-points-slider/smile-points-slider.html
> +<script type="https://cdnjs.com/libraries/currencyformatter.js"></script>
It's 33kb, not huge or anything. We decided to keep this as low-tech as possible, i.e. not trying to read the merchants currency settings from our API or turn this into a huge task.

Originally I just had a [couple vars](https://github.com/smile-io/code-samples/pull/39/commits/2a2e92d412096b02ca27b8da3f99b1bb3c8e0aa8) for symbol and symbol placement, but see Nate's [comment](https://github.com/smile-io/code-samples/pull/39#issuecomment-742638557), we wanted to at least add a little bit more accuracy and flexibility with formatting the currency. I'm open to other ideas but this feels like a good compromise in giving merchants a good amount of control without going too overboard.

2020-12-17 07:57 UTC, vladucu commented on bigcommerce-points-slider/smile-points-slider.html
> +<script type="https://cdnjs.com/libraries/currencyformatter.js"></script>
Cool, thx for the details.
Any reason we chose this specific lib? What other options did we look at?

2020-12-17 15:29 UTC, tomnez commented on bigcommerce-points-slider/smile-points-slider.html
> +<script type="https://cdnjs.com/libraries/currencyformatter.js"></script>
@vladucu I went with this because it has 700+ locales and a lot of different currency formats. I found a few other libs for formatting currency, but none of them had good support for changing locales or currency codes. They all seem to be geared towards only formatting USD.

Here's their site if you want to take a look - https://osrec.github.io/currencyFormatter.js/

2021-01-06 10:23 UTC, vladucu commented
tagging @GrizzlyNacho too, since he's more familiar with what we need here

2021-01-06 16:57 UTC, GrizzlyNacho requested changes
Thanks for the update Tom! Just a couple notes that should help language compatibility.

2021-01-06 16:57 UTC, GrizzlyNacho commented on bigcommerce-points-slider/smile-points-slider.html
> +      return formatted + ' off';
"off" is also a string they'll want to translate. Consider providing sentences with some very basic templating so that languages with different structures don't have to work with our concatenation order the same way.
Ex: Instead of `formatted + ' off'`, provide the merchant with something like `var translatedDiscount = '{{amount}} off';` and do the basic templating replacement in our code snippet.

2021-01-06 16:57 UTC, GrizzlyNacho commented on bigcommerce-points-slider/smile-points-slider.html
> +<script type="https://cdnjs.com/libraries/currencyformatter.js"></script>
Can you update this to use the min version please?

2021-01-06 16:57 UTC, GrizzlyNacho commented on bigcommerce-points-slider/smile-points-slider.html
> +    var translateYouHave = 'You have';
We should provide the full string with basic templating so that they don't need to work within the english assumed concatenation. I left an example below for the ' off' case.

2021-01-07 13:55 UTC, vladucu commented on bigcommerce-points-slider/smile-points-slider.html
> +<script type="https://cdnjs.com/libraries/currencyformatter.js"></script>
can this be loaded async?

2021-01-20 20:11 UTC, tomnez commented on bigcommerce-points-slider/smile-points-slider.html
> +    var translateYouHave = 'You have';
@GrizzlyNacho the _"off"_ case is pretty simple and has been added, but as for the _"You have 100 points"_ type of label, it's a bit more complicated because we have some HTML around certain parts of that phrase. The full example of what we currency have is:

```html
<div class="smile-points-balance-heading">' + translateYouHave + ' <span class="smile-points-balance">' + customerPointsBalance + '</span> ' + translatePointsLabel + '</div> \
```

which is part of an even [bigger block](https://github.com/smile-io/code-samples/blob/49bf6906410aece19059bfb57815848a0a2d18b9/bigcommerce-points-slider/smile-points-slider.html#L130-L150) of HTML currently.

Do you think we should move that entire block into a variable and just make sure the docs are super clear in regards to what nodes/classes need to surround the different text? I get worried about non-experienced people (with code/html) editing too much, especially in the case of translating to other languages since the words might need to be rearranged in a different order. Even with docs it leaves more room for errors which leads to more support requests, etc.

2021-01-20 20:32 UTC, GrizzlyNacho commented on bigcommerce-points-slider/smile-points-slider.html
> +    var translateYouHave = 'You have';
@tomnez I agree that I wouldn't want a merchant to need to be tweaking lines that also have html in them. What I advocate for is to keep translations all in one section of our snippet and to provide some very basic templating for them to minimize the edits they need to do but maximize our flexibility. Here's an example of what I'm thinking:
```
// This phrase will have NUMBER_POINTS replaced with the number of points the customer has
// This phrase will also have POINTS_LABEL replaced with your label above.
// Ex: 'You have NUMBER_POINTS POINTS_LABEL' would show as 'You have 120 points'
var translateYouHave = 'You have NUMBER_POINTS POINTS_LABEL';

// This phrase will have MINIMUM_AMOUNT replaced with the number of points the customer needs to redeem.
// This phrase will also have POINTS_LABEL replaced with your label above.
// Ex: 'You need a minimum of MINIMUM_AMOUNT POINTS_LABEL to redeem.' would show as 'You need a minimum of 10 points to redeem.'
var translateRewardNameRedeemLabel = 'You need a minimum of MINIMUM_AMOUNT POINTS_LABEL to redeem.'

// This phrase will have DISCOUNT_AMOUNT replaced with the currency amount to be discounted.
// Ex: 'DISCOUNT_AMOUNT off' would show as '$15 off' or '15 CAD off' depending on your preference above.
var translatedDiscount = 'DISCOUNT_AMOUNT off';
```

2021-01-20 20:40 UTC, GrizzlyNacho reviewed
I feel like we're close but not quite there yet. I know the scope of this task has increased, so please feel free to bump the story point value on it for future reference.

2021-01-21 21:10 UTC, GrizzlyNacho commented on bigcommerce-points-slider/smile-points-slider.html
> +    // Do not remove `SLIDER_VALUE` or `POINTS_LABEL` from the phrase, this will happen automatically.
Can you pop an example here please? They're so powerful for illustrating what you mean.

2021-01-21 21:12 UTC, GrizzlyNacho approved these changes

2021-01-21 21:12 UTC, GrizzlyNacho commented on shopify-points-slider/smile-points-slider.liquid
> +    // Do not remove `SLIDER_VALUE` or `POINTS_LABEL` from the phrase, this will happen automatically.
An example would help here too.

2021-01-22 08:15 UTC, vladucu approved these changes
I added a comment here on why we did this, maybe I'm missing something, regardless, I trust Nate's judgement here. 🚢

2021-01-22 08:15 UTC, vladucu commented on bigcommerce-points-slider/smile-points-slider.html
> +    var translateRewardNameRedeemLabel = 'You need a minimum of MINIMUM_AMOUNT POINTS_LABEL to redeem.'
I feel like pulling all these translatable values in separate variables made this script even messier than before.
Personally, I'd prefer to keep this script as simple as possible and have some doc for translating since this code really doesn't needs to be like this on the merchant's store 😬

2021-01-23 22:32 UTC, tomnez commented
FYI pushed up a small change to add a comment above each variable, which I reference in the [docs update](https://github.com/smile-io/docs-next/pull/1) for this addition.

2021-02-04 23:52 UTC, merged